{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ pluck  $.Values.environment $.Values.serviceAccount.name | first | default  $.Values.serviceAccount.name.default  }}
  labels:
{{ include "example.labels" . | indent 4 }}
{{- end -}}
